version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  backend:
    build: ./backend
    ports:
      - 3333:3333
    volumes:
      - ./backend/src:/src
    environment:
      VIRTUAL_HOST: adonis.site
      VIRTUAL_PORT: 3333