version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  backend:
    build: ./backend
    ports:
      - 3333:3333
    volumes:
      - ./backend/src:/src
    environment:
      VIRTUAL_HOST: adonis.local

  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mariadb:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    ports:
      - 8282:80
    environment:
      VIRTUAL_HOST: db.adonis.local
      PMA_HOST: mariadb
